// Generated by tools/commits.mjs on 2026-10-06 from each repository's git log. Do not edit by hand: run the script again.
export type RepoSummary = {
  slug: string;
  name: string;
  branch: string;
  /** first and last commit day, YYYY-MM-DD */
  first: string;
  last: string;
  /** calendar days from the first commit day to the last, both included */
  days: number;
  total: number;
  generated: string;
};

export const repos: RepoSummary[] = [
  {
    "slug": "dewex",
    "name": "Dewex",
    "branch": "main",
    "first": "2026-07-05",
    "last": "2026-10-05",
    "days": 93,
    "total": 2390,
    "generated": "2026-10-06"
  },
  {
    "slug": "dewex-os",
    "name": "Dewex OS",
    "branch": "main",
    "first": "2026-06-08",
    "last": "2026-10-06",
    "days": 121,
    "total": 1492,
    "generated": "2026-10-06"
  },
  {
    "slug": "swiss-local-adventures",
    "name": "Swiss Local Adventures",
    "branch": "main",
    "first": "2025-10-15",
    "last": "2026-10-05",
    "days": 356,
    "total": 209,
    "generated": "2026-10-06"
  },
  {
    "slug": "riview",
    "name": "riview.me",
    "branch": "main",
    "first": "2025-02-22",
    "last": "2025-07-07",
    "days": 136,
    "total": 80,
    "generated": "2026-10-06"
  }
];

/** The summary of one repository; throws on an unknown slug so a typo fails the build. */
export function repoOf(slug: string): RepoSummary {
  const r = repos.find((x) => x.slug === slug);
  if (!r) throw new Error(`no commit summary for ${slug}`);
  return r;
}
