#!/usr/bin/env node
/**
 * Reads the git history of the products and writes the one source the site uses for commits:
 *   public/commits/all.json      every commit of every product on one timeline (day, time, short
 *                                hash, subject, product), fetched by the hero
 *   src/content/commits.ts       the summary per repository, read by the numbers on the site
 *
 * Run it on this machine before a release:  node tools/commits.mjs
 *
 * Subjects are published as written, except what must never be public: emails, links, IP
 * addresses, phone numbers, and every name listed in tools/commits.redact.local.txt (one per
 * line; the file is git-ignored because the list itself must not be published).
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** The repositories shown in the hero, in the order of its legend (and of its colours). */
const REPOS = [
  { slug: 'dewex', name: 'Dewex', path: '~/Documents/Business/Dewex/Dewex-Software/dewex-app', branch: 'main' },
  { slug: 'dewex-os', name: 'Dewex OS', path: '~/Documents/Business/Dewex/Dewex-Software/dewex-os', branch: 'main' },
  { slug: 'swiss-local-adventures', name: 'Swiss Local Adventures', path: '~/Documents/Business/Dewex/Client/Swiss Local Adventures/dev/swisslocalaventures', branch: 'main' },
];

const denyList = (() => {
  const file = join(ROOT, 'tools/commits.redact.local.txt');
  if (!existsSync(file)) return [];
  return readFileSync(file, 'utf8').split('\n').map((l) => l.trim()).filter((l) => l && !l.startsWith('#'));
})();

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** What must never leave this machine, replaced by a neutral marker. */
function redact(subject, names = denyList) {
  let s = subject
    .replace(/[\w.+-]+@[\w-]+(\.[\w-]+)+/g, '[email]')
    .replace(/\bhttps?:\/\/\S+/g, '[link]')
    .replace(/\b\d{1,3}(\.\d{1,3}){3}\b/g, '[ip]')
    .replace(/\+\d[\d .-]{7,}\d|\b0\d([ .]?\d{2}){4}\b/g, '[phone]');
  for (const name of names) s = s.replace(new RegExp(`\\b${escapeRe(name)}\\b`, 'gi'), '[client]');
  return s;
}

const DAY = 86_400_000;
const dayOf = (iso) => Date.parse(`${iso}T00:00:00Z`);

function extract(repo) {
  const path = repo.path.replace(/^~/, homedir());
  const out = execFileSync('git', ['-C', path, 'log', repo.branch, '--reverse', '--format=%h%x09%ad%x09%s', '--date=format:%Y-%m-%d %H:%M'], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  const rows = out.trimEnd().split('\n').map((line) => {
    const [hash, stamp, ...rest] = line.split('\t');
    const [date, time] = stamp.split(' ');
    return { hash: hash.slice(0, 7), date, time, subject: rest.join('\t') };
  });
  const first = rows.reduce((min, r) => (r.date < min ? r.date : min), rows[0].date);
  const last = rows.reduce((max, r) => (r.date > max ? r.date : max), rows[0].date);
  return { slug: repo.slug, name: repo.name, branch: repo.branch, first, last, days: Math.round((dayOf(last) - dayOf(first)) / DAY) + 1, rows };
}

const generated = new Date().toISOString().slice(0, 10);
const histories = REPOS.map(extract);
const summaries = histories.map(({ slug, name, branch, first, last, days, rows }) => ({ slug, name, branch, first, last, days, total: rows.length, generated }));
for (const s of summaries) console.log(`${s.slug}: ${s.total} commits, ${s.first} to ${s.last} (${s.days} days)`);

// one timeline for every product; git log --reverse is in topological order, the timeline wants the clock's
const first = summaries.reduce((min, s) => (s.first < min ? s.first : min), summaries[0].first);
const last = summaries.reduce((max, s) => (s.last > max ? s.last : max), summaries[0].last);
const commits = histories
  .flatMap((h, repo) => h.rows.map((r) => [Math.round((dayOf(r.date) - dayOf(first)) / DAY), r.time, r.hash, redact(r.subject), repo]))
  .sort((a, b) => a[0] - b[0] || a[1].localeCompare(b[1]));
mkdirSync(join(ROOT, 'public/commits'), { recursive: true });
writeFileSync(join(ROOT, 'public/commits/all.json'), JSON.stringify({
  repos: summaries.map(({ slug, name, branch, total }) => ({ slug, name, branch, total })),
  first, last, days: Math.round((dayOf(last) - dayOf(first)) / DAY) + 1, total: commits.length, commits,
}));
console.log(`all: ${commits.length} commits, ${first} to ${last}`);

writeFileSync(join(ROOT, 'src/content/commits.ts'), `// Generated by tools/commits.mjs on ${generated} from each repository's git log. Do not edit by hand: run the script again.
export type RepoSummary = {
  slug: string;
  name: string;
  branch: string;
  /** first and last commit day, YYYY-MM-DD */
  first: string;
  last: string;
  /** calendar days from the first commit day to the last, both included */
  days: number;
  total: number;
  generated: string;
};

export const repos: RepoSummary[] = ${JSON.stringify(summaries, null, 2)};

/** The summary of one repository; throws on an unknown slug so a typo fails the build. */
export function repoOf(slug: string): RepoSummary {
  const r = repos.find((x) => x.slug === slug);
  if (!r) throw new Error(\`no commit summary for \${slug}\`);
  return r;
}
`);
